# Utiliser Node.js 22.5.1
FROM node:22.5.1-alpine

WORKDIR /app

# Copier les fichiers de configuration d'abord (pour optimiser le cache)
COPY package*.json ./

# Installer Angular CLI globalement
RUN npm install -g @angular/cli

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

# Exposer le port 4200
EXPOSE 4200

# Lancer le serveur de développement Angular
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]