version: '3.8'

services:
  backend:
    image : jozef952/bank-backend:v1
    container_name: ebanking-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ebanking.c0x6q2u2yn60.us-east-1.rds.amazonaws.com:5432/ebanking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: youssef123
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    image : jozef952/bank-frontend-client:v2
    container_name: ebanking-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: on-failure

  frontend-admin:
    image : jozef952/bank-frontend-admin:v2
    container_name: ebanking-frontend-admin
    ports:
      - "4100:4100"
    depends_on:
      - backend
    restart: on-failure
